### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by skuran** [share-extras/audit-dashlet#5]
v0.54 is having problems with Alfresco Community v4.2.e . While configuring enabled audit applications won't pop-up. Even if configured manually, dashlet results in Data Error. v0.53 is working as expected.

**Comment by romainguinot** [comment]
i had made a minor change in 0.54 so that the list would pop when clearing the application field in the config dialog, so that the list would pop again even with 0-length field. 

However when i tried it before committing i had no issue. 
Could you give more details wrt the error ? an exception in the log maybe ? 

I'm quite busy atm so not sure exactly when i'll be able to address it, but if i manage to reproduce your issue i might revert that change. 
Good to know it's working on 0.53 at least.

**Comment by romainguinot** [comment]
Upon further review, it appears that the error is due to lack of JSON.parse() support in your version. 
This was added some time ago in the respective latest service pack releases for the 3.4, and 4.x series. 

I had only checked against those when making this change. 

I will keep the change in place for now, because it improves parsing performance and security. So if you are not a latest service pack release or a community version that has support for this, you need to use 0.53. There are no functional differences other than that between the two. 

I might update the readme and release a 0.55 to further explain this. I will update the release notes for 0.54 in the meantime. 

Thanks for reporting it! 

Regards,
Romain.

**Comment by romainguinot** [comment]
fyi i've pushed a new release that reverts back to the "old" json parsing utilities, but now without the need to use eval calls. 

Therefore this one should again work against all previously supported releases.
